// @generated by scripts/generate_acceptance_tests.py — DO NOT EDIT.
// Source of truth: jpc.fit.nativeUITests/Features/*.feature
// Regenerate with: python3 scripts/generate_acceptance_tests.py
import XCTest

extension AcceptanceTests {


    // MARK: - Calories Tab

    func test_View_today_s_food_list() throws {
        try runScenario(feature: "calories.feature", scenario: "View today's food list")
    }

    func test_Navigate_to_previous_day() throws {
        try runScenario(feature: "calories.feature", scenario: "Navigate to previous day")
    }


    // MARK: - User Login

    func test_Successful_login() throws {
        try runScenario(feature: "login.feature", scenario: "Successful login")
    }


    // MARK: - Quotes Tab

    func test_View_quotes() throws {
        try runScenario(feature: "quotes.feature", scenario: "View quotes")
    }


    // MARK: - Settings Tab

    func test_View_settings() throws {
        try runScenario(feature: "settings.feature", scenario: "View settings")
    }


    // MARK: - Stats Tab

    func test_View_stats() throws {
        try runScenario(feature: "stats.feature", scenario: "View stats")
    }


    // MARK: - Weight Tab

    func test_View_weight_tab() throws {
        try runScenario(feature: "weight.feature", scenario: "View weight tab")
    }

}
